import {StyleSheet} from 'react-native';

export const loginStyles = StyleSheet.create({
  screen: {
    flex: 1,
    marginTop: 30,
    marginVertical: 15,
  },
  title: {
    color: 'black',
    alignSelf: 'center',
    marginTop: 80,
    fontSize: 26,
    marginRight: 10,
    marginLeft: 15,
    marginBottom: 20,
  },
  text: {
    color: 'black',
    marginTop: 30,
    margin: 30,
    fontSize: 16,
  },
  input: {
    borderBottomColor: 'black',
    borderBottomWidth: 2,
    backgroundColor: '#DBEBFF',
    height: 35,
    fontSize: 22,
  },
  codeFieldRoot: {marginTop: 20},
  cell: {
    width: 40,
    height: 40,
    lineHeight: 30,
    fontSize: 24,
    borderWidth: 0 /* 
    backgroundColor: 'gray', */,
    borderBottomColor: 'black',
    borderBottomWidth: 2 /* 
    borderColor: '#7a00002f', */,
    textAlign: 'center',
  },
  focusCell: {
    borderColor: '#bb4747',
  },
  flagInputText: {
    color: 'black',
    fontSize: 22,
    backgroundColor: '#f1f1f1',
    borderRadius: 50,
    height: 40,
    marginRight: 50,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  flagStyle: {
    width: 1,
    height: 1,
    borderWidth: 0,
  },
  backButton: {position: 'absolute', zIndex: 999999999, left: 20},
  inputName: {
    width: '85%',
    alignSelf: 'center',
    borderRadius: 50,
    marginHorizontal: 10,
    marginBottom: 20,
    backgroundColor: '#f1f1f1',
    height: 50,
    fontSize: 22,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  button: {
    marginTop: 5,
    paddingHorizontal: 30,
    alignSelf: 'center',
    width: '40%',
    borderRadius: 50,
    padding: 5,
    marginBottom: 80,

    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  textButton: {
    alignSelf: 'center',
    color: 'white',
    fontSize: 20,
    marginHorizontal: 15,
  },
});
