export const provincias = [
  {
    nombre: 'La Habana',
    municipios: [
      'Arroyo Naranjo',
      'Boyeros',
      'Centro Habana',
      'Cotorro',
      'Diez de Octubre',
      'El Cerro',
      'Guanabacoa',
      'La Habana del Este',
      'La Habana Vieja',
      'La Lisa',
      'Marianao',
      'Playa',
      'Plaza de la Revolución',
      'Regla',
      'San Miguel del Padrón',
    ],
  },
  {
    nombre: 'Pinar del Río',
    municipios: [
      'Pinar del Río',
      'Consolación del Sur',
      'Guane',
      'La Palma',
      'Los Palacios',
      'Mantua',
      'Minas de Matahambre',
      'San Juan y Martínez',
      'San Luis',
      'Sandino',
      'Viñales',
    ],
  },
  {
    nombre: 'Artemisa',
    municipios: [
      'Artemisa',
      'Alquízar',
      'Bahía Honda',
      'Bauta',
      'Caimito',
      'Candelaria',
      'Guanajay',
      'Güira de Melena',
      'Mariel',
      'San Antonio de los Baños',
      'San Cristóbal',
    ],
  },
  {
    nombre: 'Mayabeque',
    municipios: [
      'San José de las Lajas',
      'Batabanó',
      'Bejucal',
      'Güines',
      'Jaruco',
      'Madruga',
      'Melena del Sur',
      'Nueva Paz',
      'Quivicán',
      'San Nicolás',
      'Santa Cruz del Norte',
    ],
  },

  {
    nombre: 'Matanzas',
    municipios: [
      'Matanzas',
      'Calimete',
      'Cárdenas',
      'Ciénaga de Zapata',
      'Colón',
      'Jagüey Grande',
      'Jovellanos',
      'Limonar',
      'Los Arabos',
      'Martí',
      'Pedro Betancourt',
      'Perico',
      'Unión de Reyes',
    ],
  },
  {
    nombre: 'Cienfuegos',
    municipios: [
      'Cienfuegos',
      'Abreus',
      'Aguada de Pasajeros',
      'Cruces',
      'Cumanayagua',
      'Lajas',
      'Palmira',
      'Rodas',
    ],
  },
  {
    nombre: 'Villa Clara',
    municipios: [
      'Santa Clara',
      'Caibarién',
      'Camajuaní',
      'Cifuentes',
      'Corralillo',
      'Encrucijada',
      'Manicaragua',
      'Placetas',
      'Quemado de Güines',
      'Ranchuelo',
      'Remedios',
      'Sagua la Grande',
      'Santo Domingo',
    ],
  },
  {
    nombre: 'Sancti Spíritus',
    municipios: [
      'Sancti Spíritus',
      'Cabaiguán',
      'Fomento',
      'Jatibonico',
      'La Sierpe',
      'Taguasco',
      'Trinidad',
      'Yaguajay',
    ],
  },
  {
    nombre: 'Ciego de Ávila',
    municipios: [
      'Ciego de Ávila',
      'Baraguá',
      'Bolivia',
      'Chambas',
      'Ciro Redondo',
      'Florencia',
      'Majagua',
      'Morón',
      'Primero de Enero',
      'Venezuela',
    ],
  },
  {
    nombre: 'Camagüey',
    municipios: [
      'Camagüey',
      'Céspedes',
      'Esmeralda',
      'Florida',
      'Guáimaro',
      'Jimaguayú',
      'Minas',
      'Najasa',
      'Nuevitas',
      'Santa Cruz del Sur',
      'Sibanicú',
      'Sierra de Cubitas',
      'Vertientes',
    ],
  },
  {
    nombre: 'Las Tunas',
    municipios: [
      'Las Tunas',
      'Amancio',
      'Colombia',
      'Jesús Menéndez',
      'Jobabo',
      'Majibacoa',
      'Manatí',
      'Puerto Padre',
    ],
  },
  {
    nombre: 'Holguín',
    municipios: [
      'Holguín',
      'Antilla',
      'Báguanos',
      'Banes',
      'Cacocum',
      'Calixto García',
      'Cueto',
      'Frank País',
      'Gibara',
      'Mayarí',
      'Moa',
      'Rafael Freyre',
      'Sagua de Tánamo',
      'Urbano Noris',
    ],
  },
  {
    nombre: 'Granma',
    municipios: [
      'Bayamo',
      'Bartolomé Masó',
      'Buey Arriba',
      'Campechuela',
      'Cauto Cristo',
      'Guisa',
      'Jiguaní',
      'Manzanillo',
      'Media Luna',
      'Niquero',
      'Pilón',
      'Río Cauto',
      'Yara',
    ],
  },
  {
    nombre: 'Santiago de Cuba',
    municipios: [
      'Santiago de Cuba',
      'Contramaestre',
      'Guamá',
      'Mella',
      'Palma Soriano',
      'San Luis',
      'Segundo Frente',
      'Songo – La Maya',
      'Tercer Frente',
    ],
  },
  {
    nombre: 'Guantánamo',
    municipios: [
      'Guantánamo',
      'Baracoa',
      'Caimanera',
      'El Salvador',
      'Imías',
      'Maisí',
      'Manuel Tames',
      'Niceto Pérez',
      'San Antonio del Sur',
      'Yateras',
    ],
  },
  {
    nombre: 'Isla de la Juventud',
    municipios: ['Isla de la Juventud'],
  },
];
