// Generated by https://quicktype.io

export interface Home {
  _id?: ID;
  count?: number;
  description?: any[];
  weight?: number;
  currency?: Currency;
  images?: HomeImage[];
  status?: boolean;
  cost?: number;
  price?: number;
  priceGalore?: number;
  stock?: number;
  aviableSizes?: any[];
  name?: string;
  category?: Category;
  createdAt?: string;
  updatedAt?: string;
  id?: string;
  image?: HomeImage;
  nearOwners?: any[];
}

export interface ID {
  name: string;
  id: string;
  price: number;
  images: ImageElement[];
  weight: number;
  currency: Currency;
  status: boolean;
  priceGalore: number;
  description?: any[];
}

export enum Currency {
  Usd = 'USD',
}

export interface ImageElement {
  url: string;
  id: string;
  props?: Props;
}

export interface Props {
  style: Style;
  source: Source;
}

export interface Source {
  uri: string;
}

export interface Style {
  width: number;
  height: number;
}

export interface Category {
  name: string;
  id: string;
}

export interface HomeImage {
  url: string;
  id: string;
}
