// Generated by https://quicktype.io

import {Prices} from './Prices.interface';
import {CarItemProps} from './Shop.Interface';
import {Carnet} from './CarnetResponse.interface';
import {RellenoInterface} from '../screens/Shop/ShopScreen';
import {CantPaqOS} from './CantPaq.interface';

export interface OrderResponse {
  count: number;
  page: number;
  totalPages: number;
  data: Order[];
}

export interface Order {
  car: CarItemProps[];
  currency: Currency;
  user: string;
  cost: number;
  createdAt: string;
  updatedAt: string;
  id: string;
  cantPaqOS: CantPaqOS;
  totalPaqReCalc: number;
  prices: Prices;
  selectedCarnet: Carnet[];
  relleno: RellenoInterface;
}

export enum Currency {
  Usd = 'USD',
}
