// Generated by https://quicktype.io

export interface PricesResponse {
  prices: Prices;
}

export interface Prices {
  mlc: number;
  mn: number;
  oneandhalfkgPrice: number;
  twokgPrice: number;
  threekgPrice: number;
  fourkgPrice: number;
  fivekgPrice: number;
  sixkgPrice: number;
  sevenkgPrice: number;
  eigthkgPrice: number;
  ninekgPrice: number;
  tenkgPrice: number;
  createdAt?: string;
  updatedAt?: string;
  id?: string;
}
