// Generated by https://quicktype.io

export interface PricesResponse {
  prices: Prices;
}

export interface Prices {
  mlc: number;
  mn: number;
  rate: number;
  oneandhalfkgPrice: number;
  twokgPrice: number;
  threekgPrice: number;
  fourkgPrice: number;
  fivekgPrice: number;
  sixkgPrice: number;
  sevenkgPrice: number;
  eightkgPrice: number;
  ninekgPrice: number;
  tenkgPrice: number;
  elevenkgPrice: number;
  twelvekgPrice: number;
  thirteenkgPrice: number;
  fourteenkgPrice: number;
  fifteenkgPrice: number;
  sixteenkgPrice: number;
  seventeenkgPrice: number;
  eighteenkgPrice: number;
  nineteenkgPrice: number;
  twentykgPrice: number;
  createdAt?: string;
  updatedAt?: string;
  id?: string;
}
