// Generated by https://quicktype.io

export interface TrackResp {
    datos:     Dato[];
    p_origen:  string;
    p_destino: Destino;
    timeline:  string;
    error:     string;
}

export interface Dato {
    oficina_origen:  OficinaOrigen;
    oficina_destino: Destino;
    fecha:           string;
    peso:            string;
    estado:          string;
}

export enum Destino {
    CCPSanctiSpiritus = "CCP Sancti Spiritus",
    Empty = " ",
    FomentoP = "Fomento (P)",
}

export enum OficinaOrigen {
    CCPSanctiSpiritus = "CCP Sancti Spiritus",
    FomentoP = "Fomento (P)",
    OficinaCambioInternacional = "Oficina Cambio Internacional",
}
